### ISSUE TITLE
wrong index after cut

### ISSUE THREAD

**Issue by apple4196** [anabadce/rotate-elasticsearch-index#1]
I tested this script to delete my ES indices, but I found that the name of my index was wrong.
My ES index is something like this:  green  open logstash-2018.03.14 yVi9TzysSfenWmkRhEMqVQ 5 1 14211860 0 51.3gb 25.6gb.

It supposed to be that the name of index after cut is 'logstash-2018.03.14', but I get 'open'.
I found that the problem is the command 'cut', because  my ES indices has 2 spaces between 'green' and 'open'.

I modified that line from INDICES=`curl $2/_cat/indices 2>&1 | grep $1 | cut -d " " -f 3` to 
INDICES=`curl $2/_cat/indices 2>&1 | grep $1 |  awk '{print $3}'`, and I can get the correct name of index.

My ES version is : 6.1.1
And cut version is: 8.4

**Comment by anabadce** [comment]
Thanks @apple4196 ! Fixed, good catch.
